name: "Automated Merging"
description: "Watch user's activity."
outputs:
  result:
    description: "Conditionally merge pull requests after a timeout."
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - run: |
        yarn --cwd ${{ github.action_path }} --production=true
      id: install
      shell: bash
    - run: yarn --cwd ${{ github.action_path }} start
      shell: bash
      id: main
